### ISSUE TITLE
Names of theories

### ISSUE THREAD

**Issue by AnthonyBordg** [AnthonyBordg/Isabelle_marries_Dirac#11]
@jaycech3n changed the name of the theory `MoreTensor.thy` to `More_Tensor.thy` and rightly so, since the former name did not respect my (implicit) own conventions about naming theories. But, he is now seen as a contributor of the file and the only one! I naively did not expect this behavior of GitHub. 
For the record, @MH2520 and I have been the only contributors of this theory so far. 
In the future, changes in the names of theories should be done by a genuine contributor, or better they should be avoided altogether (since the problem would be somewhat the same). We should get right the names of theories from the very beginning.
However, I want to say that it's not Josh's fault, it's my fault as the administrator of the repo. 
I take the opportunity to make explicit the conventions about naming theories for everyone (@Lachnitt ): underscores between words and capitals for the first letter of each word.

**Comment by jaycech3n** [comment]
My bad, though I certainly did not expect this behavior either!

**Comment by AnthonyBordg** [comment]
@jaycech3n no worry.

**Comment by AnthonyBordg** [comment]
Do you think I should revert @jaycech3n 's merged commit ?

**Comment by jaycech3n** [comment]
It would probably be better, then the change can be made by one of the actual contributors.

**Comment by AnthonyBordg** [comment]
Issue solved.
@jaycech3n do you want to open a new PR with your root file ?

**Comment by jaycech3n** [comment]
How about I just leave it to you all to add, since you've already seen how to do it (and to avoid further complications) ;)

**Comment by AnthonyBordg** [comment]
Ok.
I close the issue in this case.
